import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'css/style.css';
import css from './layout.module.css';
import { Fragment } from 'react';
import Menu from '@/components/Menu/Menu';
import Footer from '@/components/Footer/Footer';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	// title: 'Create Next App',
	// description: 'Generated by create next app',
};

// Layout.tsx ist der Einstiegspunkt der Next.js-Anwendung.
// Im Body wird App/page.tsx als Home aufgerufen.
// Routing erfolgt per Folder: Wird ein Order "Spiele" angelegt, entsteht
// eine Route /Spiele. Im Ordner muss dann eine entsprechende page.tsx liegen.

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html>
			<body className={css.siteWrapper}>
				<nav className={css.siteHeader}>
					<Menu headline={'BBCodegenerator 3.0'} />
				</nav>
				{children}
				{/* <Footer /> */}
			</body>
		</html>
	);
}
